### PR TITLE
Python3 part10

### LINKED ISSUE #71: Update support for Python 3
--------
Issue Description
--------
Much of RAVEN works with Python 3, but parts such cloud pickle and pp do not work with Python3.  

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements? __No impact__
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.  __Not a defect__
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

### PR DESCRIPTION
**Pull request by joshua-cogliati-inl**
--------
Pull Request Description
--------
##### What issue does this change request address?
Closes #71 

##### What are the significant changes in functionality due to this change request?
Removal of old getpot reader in TreeStructure.  
Changes to Rook to let it be used by PHISICS.
Allows coverage to be done from the tester. 
Allows command prefix to be added to all commands the tester calls (to for example run them with qsubs).
Adding a differ that just checks for the file to exist.
Moved OrderedCSVDiffer, XMLDiff and DiffUtils to Rook from RAVEN.
Adds a system for different types of tests to be run with different command line parameters.
Now can wait a bit for files (needed for running a cluster where the filesystem can take some time to propagate all the files)
Smooth the output of the percentage of cpu used to reduce overloading the test machine.
Converted cluster tests to use Rook.
Added a test to make sure Rook can handle megabytes of output data.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code.
- [x] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [x] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [x] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [x] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [x] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [x] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [x] 8. If an analytic test is changed/added is the the analytic documentation updated/added?

### CODE REVIEW

**Comment by joshua-cogliati-inl** [comment]
This is a work in progress, do not merge yet.

File: tests/cluster_tests/test_qsubs.sh [hunk 1]
```diff
@@ -47,146 +47,13 @@ wait_lines ()
...
-
-
-if test $num_fails -eq 0; then
-    echo ALL PASSED
-else
-    echo FAILED: $num_fails $fails
-fi
-exit $num_fails
+cd ${RAVEN_FRAMEWORK_DIR}/..
+./run_tests --only-run-types="qsub" --re=cluster_tests
```
Comment (PaulTalbot-INL) [inline tests/cluster_tests/test_qsubs.sh]: :clap::clap::clap::clap:

**Comment by PaulTalbot-INL** [comment]
I have started on this review, sorry I haven't finished yet. I'll try to wrap it up soon.

File: rook/Tester.py [hunk 2]
```diff
@@ -469,6 +570,22 @@ def run_backend(self, _):
         self.results.message += "\n" + message
     return self.results
 
+  def _wait_for_all_written(self):
+    """
+      Waits until all the files for the differ have been written
```
Comment (PaulTalbot-INL) [inline rook/Tester.py]: No In/Out docstrings included, and I don't think the standards have an exception for argument- and return-less methods.

File: rook/doc/rook.tex [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+The testers are used to run a test.  The tester can fail the test, or
+it can be failed by one of the differs that are attached as subnodes
+in the test input.
+
+\subsection{Common Features}
+
+These are the features that are common to all testers.
+
+\begin{description}
+  \item[type] The type of this test
```
Comment (PaulTalbot-INL) [inline rook/doc/rook.tex]: Could we add a little to this description to indicate what a "type" is? Is this like "normal, heavy" or like "RavenFramework, Python"?

File: rook/doc/rook.tex [hunk 4]
```diff
@@ -0,0 +1,81 @@
...
+  \item[skip] If true skip test
+  \item[prereq] list of tests to run before running this one
+  \item[max\_time] Maximum time that test is allowed to run in seconds
+  \item[os\_max\_time] Maximum time by os. Example: Linux 20 Windows 300 OpenVMS 1000
+  \item[heavy] If true, run only with heavy tests
+  \item[output] Output of the test
+  \item[expected\_fail] if true, then the test should fails, and if it passes, it fails
+  \item[run\_types] The run types that this test is
```
Comment (PaulTalbot-INL) [inline rook/doc/rook.tex]: Similar to above, I think it's more clear that `run_types` is like "heavy, qsub", but maybe listing that example would clarify at a glance which is used for which.

File: rook/doc/rook.tex [hunk 5]
```diff
@@ -0,0 +1,81 @@
...
+\subsection{XML}
+
+This can compare two XML files to see if they are the same.
+
+\begin{description}
+  \item[unordered] if true allow the tags in any order
+  \item[zero\_threshold] it represents the value below which a float is considered zero
+  \item[remove\_whitespace] Removes whitespace before comparing xml node text if True
+  \item[remove\_unicode\_identifier] if true, then remove u infront of a single quote
+  \item[xmlopts] Options for xml checking
```
Comment (PaulTalbot-INL) [inline rook/doc/rook.tex]: Do we know what acceptable options are? Maybe this is a separate PR to fill this in.

File: rook/main.py [hunk 6]
```diff
@@ -202,20 +232,28 @@ def process_result(index, _input_data, output_data):
 
   test_re = re.compile(args.test_re_raw)
 
-  #XXX fixme to find a better way to the tests directory
-
   this_dir = os.path.abspath(os.path.dirname(__file__))
   up_one_dir = os.path.dirname(this_dir)
-  base_test_dir = os.path.join(up_one_dir, "tests")
+  if args.test_dir is None:
+    #XXX fixme to find a better way to the tests directory
```
Comment (PaulTalbot-INL) [inline rook/main.py]: I assume this is still something to do in the future?

File: tests/cluster_tests/test_qsubs.sh [hunk 7]
```diff
@@ -8,7 +8,7 @@ fails=''
 
 pushd ../../framework
 RAVEN_FRAMEWORK_DIR=$(pwd)
-source ../scripts/establish_conda_env.sh --load
+#source ../scripts/establish_conda_env.sh --load
```
Comment (PaulTalbot-INL) [inline tests/cluster_tests/test_qsubs.sh]: Do these commented lines (also the ones below in this file) need to be kept?

File: developer_tools/get_coverage_tests.py [hunk 8]
```diff
@@ -74,7 +74,7 @@ def getRegressionTests(whichTests=1,skipExpectedFails=True):
       if "input" not in spec:
         continue
       testType = spec.get('type',"notfound").strip()
-      newTest = spec['input'].strip()
+      newTest = spec['input'].strip().split()[0]
```
[the remark this answers is not in the document]
Comment (joshua-cogliati-inl) [reply developer_tools/get_coverage_tests.py]: Good point.  So far as I can tell, split() basically does the strip, so the strip can be dropped.

File: framework/utils/TreeStructure.py [hunk 9]
```diff
@@ -60,10 +60,8 @@ def parse(inFile,dType=None):
     extension = inFile.name.split('.')[-1].lower()
     if extension == 'xml':
       dType = 'xml'
-    elif extension in ['i','inp','in']:
-      dType = 'getpot'
     else:
-      raise InputParsingError('Unrecognized file type for:',inFile,' | Expected .xml, .i, .in, or .inp')
+      raise InputParsingError('Unrecognized file type for:',inFile,' | Expected .xml')
```
[the remark this answers is not in the document]
Comment (joshua-cogliati-inl) [reply framework/utils/TreeStructure.py]: I added a comment to that effect.

File: rook/ExistsDiff.py [hunk 10]
```diff
@@ -0,0 +1,69 @@
...
+    Differ.__init__(self, name, params, test_dir)
+
+  def check_output(self):
+    """
+      Checks that the output matches the gold.
+      returns (same, message) where same is true if the
+      test passes, or false if the test failes.  message should
+      gives a human readable explaination of the differences.
+      @ In, None
+      @ Out, (same, message), same is true if the tests passes.
```
[the remark this answers is not in the document]
Comment (joshua-cogliati-inl) [reply rook/ExistsDiff.py]: Listed types (same is bool, message is str)

File: rook/Tester.py (hunk 2 above)
Comment (joshua-cogliati-inl) [reply rook/Tester.py]: Fixed.

File: rook/doc/rook.tex (hunk 3 above)
Comment (joshua-cogliati-inl) [reply rook/doc/rook.tex]: Added examples to run_types and type.

File: rook/doc/rook.tex (hunk 4 above)
Comment (joshua-cogliati-inl) [reply rook/doc/rook.tex]: Fixed.

File: rook/doc/rook.tex (hunk 5 above)
Comment (joshua-cogliati-inl) [reply rook/doc/rook.tex]: Hm, looking they seem to be unordered, rel_err, zero_threshold, remove_whitespace, and remove_unicode_identifier, all of which are already top level options at this point.  I think possibly we should have a separate pull request to remove xmlopts.  I added: Deprecated, the options should be used directly instead of using this (as in use the unordered tag instead of putting it in xmlopts)

File: rook/main.py (hunk 6 above)
Comment (joshua-cogliati-inl) [reply rook/main.py]: Yes, this probably should be done when we split rook to a separate repository.

File: tests/cluster_tests/test_qsubs.sh (hunk 7 above)
Comment (joshua-cogliati-inl) [reply tests/cluster_tests/test_qsubs.sh]: Removed commented out lines.

**Comment by PaulTalbot-INL** [comment]
Approved for merge pending successful completion of the regression tests.

File: tests/cluster_tests/test_qsubs.sh [hunk 11]
```diff
@@ -47,146 +46,5 @@ wait_lines ()
...
-
-
-if test $num_fails -eq 0; then
-    echo ALL PASSED
-else
-    echo FAILED: $num_fails $fails
-fi
-exit $num_fails
+cd ${RAVEN_FRAMEWORK_DIR}/..
+./run_tests --only-run-types="qsub" --re=cluster_tests
```
Comment (PaulTalbot-INL) [inline tests/cluster_tests/test_qsubs.sh]: Doesn't need to be on this PR, but could we potentially parallelize these qsub tests?
