### PR TITLE
Closes #673

### LINKED ISSUE #583: No tests for non-"time" ROM pivots
--------
Issue Description
--------
There are few coverage tests for time-dependent scikitlearn ROMs, and apparently none of them uses the pivotParameter node.  We should add testing to time-dependent ROMs to cover basic utility.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

### LINKED ISSUE #673: DMD ROM not well pickled
--------
Issue Description
--------
##### What did you expect to see happen?

The pickled DMD ROM to function well on propagating data over a uniform grid.

##### What did you see instead?

Error messages regarding failed jobs:

Traceback (most recent call last):
  File "/apps/local/easybuild/software/Python/2.7.9-gmvolf-5.5.4/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/apps/local/easybuild/software/Python/2.7.9-gmvolf-5.5.4/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/chenj/RAVEN/projects/raven/framework/Runners/SharedMemoryRunner.py", line 135, in <lambda>
    self.thread = threading.Thread(target = lambda q, *arg : q.append(self.functionToRun(*arg)), name = self.identifier, args=(self.subque,)+tuple(self.args))
  File "/home/chenj/RAVEN/projects/raven/framework/Models/ROM.py", line 427, in evaluateSample
    result = self._externalRun(inRun)
  File "/home/chenj/RAVEN/projects/raven/framework/Models/ROM.py", line 406, in _externalRun
    returnDict = self.evaluate(inRun)
  File "/home/chenj/RAVEN/projects/raven/framework/Models/ROM.py", line 394, in evaluate
    outputEvaluation = self.supervisedEngine.evaluate(inputToROM)
  File "/home/chenj/RAVEN/projects/raven/framework/LearningGate.py", line 200, in evaluate
    sliceEvaluation = rom.evaluate(request)
  File "/home/chenj/RAVEN/projects/raven/framework/SupervisedLearning.py", line 272, in evaluate
    return self.__evaluateLocal__(featureValues)
  File "/home/chenj/RAVEN/projects/raven/framework/SupervisedLearning.py", line 3325, in __evaluateLocal__
    weights, indexes = self.KDTreeFinder.query(featureVals, k=min(2**len(self.features),len(reconstructData)))
  File "/apps/local/easybuild/software/Python/2.7.9-gmvolf-5.5.4/lib/python2.7/site-packages/scipy/spatial/kdtree.py", line 497, in query
    hits = self.__query(x[c], k=k, eps=eps, p=p, distance_upper_bound=distance_upper_bound)
  File "/apps/local/easybuild/software/Python/2.7.9-gmvolf-5.5.4/lib/python2.7/site-packages/scipy/spatial/kdtree.py", line 365, in __query
    if x[node.split_dim] < node.split:
AttributeError: 'leafnode' object has no attribute 'split_dim'

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

[L&S_DMD.xml.zip](https://github.com/idaholab/raven/files/2069709/L.S_DMD.xml.zip)

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

### LINKED ISSUE #695: SINGLE RUN with HDF5 crash
--------
Issue Description
[relap_pwr_loca_sampler.txt](https://github.com/idaholab/raven/files/2207129/relap_pwr_loca_sampler.txt)

--------
##### What did you expect to see happen?
N/A

##### What did you see instead?
(    0.04 sec) SIMULATION               : Message         -> -- Beginning step sampleRELAP of type: SingleRun                    --
(    0.04 sec) STEP SINGLERUN           : Message         -> ***  Beginning initialization ***
(    0.04 sec) STEP SINGLERUN           : Message         -> ***    Initialization done    ***
(    0.04 sec) STEP SINGLERUN           : Message         -> ***       Beginning run       ***
(    0.04 sec) Code                     : Message         -> job "None" submitted!
(    0.06 sec) Code                     : Message         -> Execution command submitted: /usr/local/tools/RELAP53D_INL/4.3.4/SLE12/relap/bin/relap5.x -i typpwr_PTC.i -o out~typpwr_PTC.o   
Traceback (most recent call last):
  File "/home/wmorrison/RAVEN_July_18/raven/framework/Driver.py", line 281, in <module>
    raven()
  File "/home/wmorrison/RAVEN_July_18/raven/framework/Driver.py", line 234, in raven
    simulation.run()
  File "/home/wmorrison/RAVEN_July_18/raven/framework/Simulation.py", line 791, in run
    stepInstance.takeAstep(stepInputDict)
  File "/home/wmorrison/RAVEN_July_18/raven/framework/Steps.py", line 312, in takeAstep
    self._localTakeAstepRun(inDictionary)
  File "/home/wmorrison/RAVEN_July_18/raven/framework/Steps.py", line 462, in _localTakeAstepRun
    model.collectOutput(finishedJob,output)
  File "/home/wmorrison/RAVEN_July_18/raven/framework/Models/Code.py", line 667, in collectOutput
    output.addRealization(evaluation)
  File "/home/wmorrison/RAVEN_July_18/raven/framework/Databases.py", line 248, in addRealization
    self.database.addGroup(rlz)
  File "/home/wmorrison/RAVEN_July_18/raven/framework/h5py_interface_creator.py", line 189, in addGroup
    groupName = str(rlz.get("prefix")[0] if not isinstance(rlz.get("prefix"),basestring) else rlz.get("prefix"))
TypeError: 'NoneType' object has no attribute '__getitem__'

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

### LINKED ISSUE #697: SPSA manual parameter naming problem
--------
Issue Description
--------

##### What did you expect to see happen?
In the manual, some of the parameters are named with a different name then what it is in the  code.
For example,
gainGrowthFactor is expected by the code, but the manual says we shoould input gainGrowthSize 

##### Do you have a suggested fix for the development team?
Fix

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

### PR DESCRIPTION
**Pull request by alfoa**
--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)
Closes #673
Closes #695 
Closes #583 
Closes #697

##### What are the significant changes in functionality due to this change request?
- Fixed the pickling and loading for DMD-based ROMs.
- Added a test in the DMD
- Fixed SingleRun prefix with HDF5 and modified a test
- Fixed manual for optimizer
- Fixed pivotParameter error for TimeDependent ROMs

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code.
- [x] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [x] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [x] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [x] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [x] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [x] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [x] 8. If an analytic test is changed/added is the the analytic documentation updated/added?

Checklist review by @wangc on July 20, 2018

### CODE REVIEW

File: crow/include/distributions/distributionNDInverseWeight.h [hunk 1]
```diff
@@ -184,6 +184,15 @@ class BasicMultiDimensionalInverseWeight: public virtual BasicDistributionND
     return value;
   }
 
+  double marginal(double x, int dimension){
```
Comment (wangcj05) [inline crow/include/distributions/distributionNDInverseWeight.h]: docstring

File: crow/src/distributions/distributionNDCartesianSpline.cxx [hunk 2]
```diff
@@ -156,14 +156,16 @@
       if (_cdf_provided){
         throwError("BasicMultiDimensionalCartesianSpline Distribution error: inverseMarginal calculation not available if CDF provided");
       }else{
-        value = _interpolator.splineCartesianInverseMarginal(f, dimension, 0.01);
+        value = _interpolator.splineCartesianInverseMarginal(f, dimension, 1.e-6);
```
Comment (wangcj05) [inline crow/src/distributions/distributionNDCartesianSpline.cxx]: Should we remove the coded value, and add a variable to control that?

File: crow/src/distributions/distributionNDCartesianSpline.cxx [hunk 3]
```diff
@@ -156,14 +156,16 @@
...
       }
     }else
       throwError("BasicMultiDimensionalCartesianSpline Distribution error: CDF value for inverse marginal distribution is above 1.0");
 
     return value;
   }
 
+
+
```
Comment (wangcj05) [inline crow/src/distributions/distributionNDCartesianSpline.cxx]: remove extra line?

File: framework/SupervisedLearning.py [hunk 4]
```diff
@@ -3229,6 +3229,15 @@ def __init__(self,messageHandler,**kwargs):
     if self.pivotParameterID not in self.target:
       self.raiseAnError(IOError,"The pivotParameter "+self.pivotParameterID+" must be part of the Target space!")
 
+  def __setstate__(self, newstate):
```
Comment (wangcj05) [inline framework/SupervisedLearning.py]: newstate or newState?

File: crow/include/distributions/distributionNDInverseWeight.h (hunk 1 above)
Comment (alfoa) [reply crow/include/distributions/distributionNDInverseWeight.h]: added

File: crow/src/distributions/distributionNDCartesianSpline.cxx (hunk 2 above)
Comment (alfoa) [reply crow/src/distributions/distributionNDCartesianSpline.cxx]: yes this is the final plan

File: crow/src/distributions/distributionNDCartesianSpline.cxx (hunk 3 above)
Comment (alfoa) [reply crow/src/distributions/distributionNDCartesianSpline.cxx]: removed

File: framework/SupervisedLearning.py (hunk 4 above)
Comment (alfoa) [reply framework/SupervisedLearning.py]: fixed

**Comment by alfoa** [comment]
Comments addressed + added unit test

**Comment by wangcj05** [comment]
The unit test that you created is failed:
```
framework/unit_tests/Distributions.Distributions: checking answer MultiVariate inverseMarginalDim1(0.5) 2999.99999881 != 3000.419
framework/unit_tests/Distributions.Distributions: checking answer MultiVariate inverseMarginalDim2(0.5) 2499.97185556 != 2500.044
```
You may need to update your checked values.

**Comment by alfoa** [comment]
ok fixed unit test and better docstrings

File: tests/framework/unit_tests/Distributions/TestDistributions.py [hunk 5]
```diff
@@ -56,16 +56,18 @@ def createElement(tag,attrib={},text={}):
...
     This method is aimed to compare two floats given a certain tolerance
     @ In, comment, string, a comment printed out if it fails
     @ In, value, float, the value to compare
     @ In, expected, float, the expected value
     @ In, tol, float, optional, the tolerance
+    @ In, relative, bool, optional, the tolerance needs be checked relative?
     @ Out, None
   """
-  if abs(value - expected) > tol:
+  diff = abs(value - expected) if not relative else abs(value - expected)/expected
```
[the remark this answers is not in the document]
Comment (alfoa) [reply tests/framework/unit_tests/Distributions/TestDistributions.py]: done

**Comment by wangcj05** [comment]
Tests are failed, how do you determine the checked value for the unit tests? are they depend on running systems?

**Comment by alfoa** [comment]
Well....I am simply pushing the value I get from the mac... The correct value should be 0.5 but unfortunately since the hard-coded discretizations     and tolerances I am not able to get it. 
I will relax the Multivariate peak to remove the wiggles of the spline.

**Comment by PaulTalbot-INL** [comment]
For the record, since we have to force library versions on Windows manually, until #668 merges the libraries will not pass on other MRs.  Just as a reminder.

**Comment by alfoa** [comment]
@wangcj05 can you review this again? It should be green now

File: framework/Steps.py [hunk 6]
```diff
@@ -399,11 +399,13 @@ def _localInitializeStep(self,inDictionary):
...
     if inDictionary['Model'].createWorkingDir:
-      currentWorkingDirectory = os.path.join(inDictionary['jobHandler'].runInfoDict['WorkingDir'],inDictionary['jobHandler'].runInfoDict['stepName'])
+      currentWorkingDirectory = os.path.join(inDictionary['jobHandler'].runInfoDict['WorkingDir'],
+                                             inDictionary['jobHandler'].runInfoDict['stepName'])
       try:
         os.mkdir(currentWorkingDirectory)
       except OSError:
-        self.raiseAWarning('current working dir '+currentWorkingDirectory+' already exists, this might imply deletion of present files')
+        self.raiseAWarning('current working dir '+currentWorkingDirectory+' already exists, ' +
+                           'this might imply deletion of present files')
```
Comment (wangcj05) [inline framework/Steps.py]: better to use ```,```  instead of ```+```, but it is fine if not change it.

File: framework/Steps.py [hunk 7]
```diff
@@ -474,13 +477,16 @@ def _localTakeAstepRun(self,inDictionary):
             if self.failureHandling['jobRepetitionPerformed'][finishedJob.identifier] <= self.failureHandling['repetitions']:
               # we re-add the failed job
               jobHandler.reAddJob(finishedJob)
-              self.raiseAWarning('As prescribed in the input, trying to re-submit the job "'+finishedJob.identifier+'". Trial '+
-                               str(self.failureHandling['jobRepetitionPerformed'][finishedJob.identifier]) +'/'+str(self.failureHandling['repetitions']))
+              self.raiseAWarning('As prescribed in the input, trying to re-submit the job "'+
+                                 finishedJob.identifier+'". Trial '+
+                               str(self.failureHandling['jobRepetitionPerformed'][finishedJob.identifier]) +
+                               '/'+str(self.failureHandling['repetitions']))
```
Comment (wangcj05) [inline framework/Steps.py]: ok here, but better to use ```,```

File: framework/Steps.py [hunk 8]
```diff
@@ -474,13 +477,16 @@ def _localTakeAstepRun(self,inDictionary):
...
               self.failureHandling['jobRepetitionPerformed'][finishedJob.identifier] += 1
             else:
               #add run to a pool that can be sent to the sampler later
               self.failedRuns.append(copy.copy(finishedJob))
-              self.raiseAWarning('The job "'+finishedJob.identifier+'" has been submitted '+ str(self.failureHandling['repetitions'])+' times, failing all the times!!!')
+              self.raiseAWarning('The job "'+finishedJob.identifier+'" has been submitted '+
+                                 str(self.failureHandling['repetitions'])+' times, failing all the times!!!')
```
Comment (wangcj05) [inline framework/Steps.py]: same as before

File: framework/SupervisedLearning.py [hunk 9]
```diff
@@ -2210,6 +2210,9 @@ def __init__(self,messageHandler,**kwargs):
     """
     supervisedLearning.__init__(self,messageHandler,**kwargs)
     name  = self.initOptionDict.pop('name','')
+    if 'pivotParameter' in self.initOptionDict:
+      # remove pivot parameter if present
+      self.initOptionDict.pop("pivotParameter")
```
Comment (wangcj05) [inline framework/SupervisedLearning.py]: I did not get here. You changed the way to retrieve the pivotParameter in the ```LearningGate```, but here you start to remove it. why?

Comment (alfoa) [reply framework/SupervisedLearning.py]: because the pivotParameter is needed internally for all the TimeDep ROMs, but not for the SKLearn ROMs., since we pass directly the dictionary into the SKL constructors (that complains in case a variable is not recognized (e.g. pivotParameter)

Comment (wangcj05) [reply framework/SupervisedLearning.py]: Got it.

**Comment by wangcj05** [comment]
This PR looks good to me. I will go through the checklist.

**Comment by alfoa** [comment]
Proposed email:

Dear users,
we recently realized that there was a mismatch between the user manual and the Code regarding the GradientBased optimizers.
The code was expecting the following two parameters:
- gainGrowthFactor and gainShrinkFactor
but in the manual they were called gainGrowthSize and gainShrinkSize.
The issue has been solved with the PR #674 and the modification is currently available in the devel branch
