### PR TITLE
Windows doc fix

### LINKED ISSUE #1874: [DEFECT] Documentation does not build on Windows
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [X] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

On Windows, the documentation is not generated when following the process described in the wiki. running the following does not generate the documentation:

`C:\projects\raven\doc> ./make_docs.sh`

### Steps to Reproduce

Running the following does not generate the documentation:

`C:\projects\raven\doc> ./make_docs.sh`

### Expected Behavior

All of the documentation should be built when running:

`C:\projects\raven\doc> ./make_docs.sh`

### Screenshots and Input Files

_No response_

### OS

Windows

### OS Version

doc_error

### Dependency Manager

CONDA

### For Change Control Board: Issue Review

- [X] Is it tagged with a type: defect or task?
- [X] Is it tagged with a priority: critical, normal or minor?
- [X] If it will impact requirements or requirements tests, is it tagged with requirements?
- [X] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [X] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

### PR DESCRIPTION
**Pull request by dgarrett622**
--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)
Fixes  and close #1874 

##### What are the significant changes in functionality due to this change request?
Documentation will build on windows by running `C:\projects\raven\doc> ./make_docs.sh`

References in manuals are now generated

Plugins manual is now generated

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code.
- [x] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [x] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [x] 4. Automated Tests should pass, including run_tests, pylint, manual building and xsd tests. If there are changes to Simulation.py or JobHandler.py the qsub tests must pass.
- [x] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. If new development on the internal JobHandler parallel system is performed, a cluster test must be added setting, in <RunInfo> XML block, the node ```<internalParallel>``` to True.
- [x] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [x] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [x] 8. If an analytic test is changed/added is the the analytic documentation updated/added?
- [x] 9. If any test used as a basis for documentation examples (currently found in `raven/tests/framework/user_guide` and `raven/docs/workshop`) have been changed, the associated documentation must be reviewed and assured the text matches the example.

### CODE REVIEW

File: doc/user_guide/make_win.sh [hunk 1]
```diff
@@ -8,16 +8,19 @@ declare -a exts=(txt ps ds)
...
 		do
-			rm -rf *.aux *.bbl *.blg *.log *.out *.toc *.lot *.lof raven_user_manual.pdf
+			rm -rf *.aux *.bbl *.blg *.log *.out *.toc *.lot *.lof *.gz raven_user_guide.pdf
 		done
 	done
 }
 
+# load raven libraries
+source ../../scripts/establish_conda_env.sh --load --quiet
+
```
Comment (wangcj05) [inline doc/user_guide/make_win.sh:23]: why do we need to load the library here?

**Review by wangcj05 — APPROVED** [review]
I have a general comment, otherwise this PR is good.

File: doc/user_guide/make_win.sh (hunk 1 above)
Comment (dgarrett622) [reply doc/user_guide/make_win.sh:23]: If the user wants to build the user guide by itself, they can run `doc\user_gude> ./make_win.sh`. In the wiki it says this:

> If only a specific document needs to be built, navigate to the containing folder and type:
> 
> In GitBash:
> 
>   `./make_win.sh`
> In PowerShell:
> 
>   `bash.exe ./make_win.sh`
> For example:
> 
> `C:\projects> cd raven\doc\user_manual`
> `C:\projects\raven\user_manual> ./make_win.sh` (In GitBash) or `bash.exe make_win.sh` (In PowerShell)
> 

It is not needed if `doc> ./make_docs.sh` is run.

Comment (wangcj05) [reply doc/user_guide/make_win.sh:23]: In this case, we probably need to load the library in each make_win.sh.

Comment (dgarrett622) [reply doc/user_guide/make_win.sh:23]: All of the other make_win.sh files run without loading the library. The user guide seems to be the only one that needs it. I'm guessing this is because the user guide takes TeX from RAVEN itself and the other manuals don't do this?

**Comment by wangcj05** [comment]
checklist is good.
